/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { EthGifter } from "../EthGifter";

export class EthGifter__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<EthGifter> {
    return super.deploy(overrides || {}) as Promise<EthGifter>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EthGifter {
    return super.attach(address) as EthGifter;
  }
  connect(signer: Signer): EthGifter__factory {
    return super.connect(signer) as EthGifter__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EthGifter {
    return new Contract(address, _abi, signerOrProvider) as EthGifter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "requestEth",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060ac8061001f6000396000f3fe608060405260043610601f5760003560e01c80631260b97e14602a576025565b36602557005b600080fd5b604460048036036020811015603e57600080fd5b50356046565b005b604051339082156108fc029083906000818181858888f193505050501580156072573d6000803e3d6000fd5b505056fea2646970667358221220b0544d00124bff61b68f525f711d3cc325124c6f47f38e7a2ea47d224287e64764736f6c634300060c0033";
