/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { TokenGifter } from "../TokenGifter";

export class TokenGifter__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<TokenGifter> {
    return super.deploy(overrides || {}) as Promise<TokenGifter>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TokenGifter {
    return super.attach(address) as TokenGifter;
  }
  connect(signer: Signer): TokenGifter__factory {
    return super.connect(signer) as TokenGifter__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenGifter {
    return new Contract(address, _abi, signerOrProvider) as TokenGifter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20Upgradeable",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "requestTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061010a806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063aa5fc79414602d575b600080fd5b605660048036036040811015604157600080fd5b506001600160a01b0381351690602001356058565b005b6040805163a9059cbb60e01b81523360048201526024810183905290516001600160a01b0384169163a9059cbb9160448083019260209291908290030181600087803b15801560a657600080fd5b505af115801560b9573d6000803e3d6000fd5b505050506040513d602081101560ce57600080fd5b5050505056fea264697066735822122032ed50b9f09b80439c7ae3a31508ebf94be5fdbe68949e6e6c79bf86315d96ba64736f6c634300060c0033";
