/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { TokenRelease } from "../TokenRelease";

export class TokenRelease__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<TokenRelease> {
    return super.deploy(overrides || {}) as Promise<TokenRelease>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TokenRelease {
    return super.attach(address) as TokenRelease;
  }
  connect(signer: Signer): TokenRelease__factory {
    return super.connect(signer) as TokenRelease__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenRelease {
    return new Contract(address, _abi, signerOrProvider) as TokenRelease;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20Upgradeable",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "giveTokensTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610186806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063be52507c14610030575b600080fd5b61009c6004803603606081101561004657600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff1690602001909291908035906020019092919050505061009e565b005b8273ffffffffffffffffffffffffffffffffffffffff1663a9059cbb83836040518363ffffffff1660e01b8152600401808373ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b15801561010f57600080fd5b505af1158015610123573d6000803e3d6000fd5b505050506040513d602081101561013957600080fd5b81019080805190602001909291905050505050505056fea26469706673582212206b161b0a103f58521325829046096f05da4f7fa81aa04b1322cc14b042558ea864736f6c634300060c0033";
