/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { TokenGifter } from "../TokenGifter";

export class TokenGifter__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<TokenGifter> {
    return super.deploy(overrides || {}) as Promise<TokenGifter>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TokenGifter {
    return super.attach(address) as TokenGifter;
  }
  connect(signer: Signer): TokenGifter__factory {
    return super.connect(signer) as TokenGifter__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenGifter {
    return new Contract(address, _abi, signerOrProvider) as TokenGifter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20Upgradeable",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "requestTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610165806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063aa5fc79414610030575b600080fd5b61007c6004803603604081101561004657600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291908035906020019092919050505061007e565b005b8173ffffffffffffffffffffffffffffffffffffffff1663a9059cbb33836040518363ffffffff1660e01b8152600401808373ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b1580156100ef57600080fd5b505af1158015610103573d6000803e3d6000fd5b505050506040513d602081101561011957600080fd5b810190808051906020019092919050505050505056fea2646970667358221220a4f2b2abaa5bc4fa173c6165b86996ab8bfda3b643e6fd1d635b5c31c40ff9eb64736f6c634300060c0033";
