/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ExampleComputeLiquidityValueInterface extends ethers.utils.Interface {
  functions: {
    "factory()": FunctionFragment;
    "getGasCostOfGetLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)": FunctionFragment;
    "getLiquidityValue(address,address,uint256)": FunctionFragment;
    "getLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)": FunctionFragment;
    "getReservesAfterArbitrage(address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetLiquidityValueAfterArbitrageToPrice",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityValue",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityValueAfterArbitrageToPrice",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesAfterArbitrage",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetLiquidityValueAfterArbitrageToPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityValueAfterArbitrageToPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesAfterArbitrage",
    data: BytesLike
  ): Result;

  events: {};
}

export class ExampleComputeLiquidityValue extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ExampleComputeLiquidityValueInterface;

  functions: {
    factory(overrides?: CallOverrides): Promise<[string]>;

    "factory()"(overrides?: CallOverrides): Promise<[string]>;

    getGasCostOfGetLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getGasCostOfGetLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLiquidityValue(
      tokenA: string,
      tokenB: string,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tokenAAmount: BigNumber;
        tokenBAmount: BigNumber;
      }
    >;

    "getLiquidityValue(address,address,uint256)"(
      tokenA: string,
      tokenB: string,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tokenAAmount: BigNumber;
        tokenBAmount: BigNumber;
      }
    >;

    getLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tokenAAmount: BigNumber;
        tokenBAmount: BigNumber;
      }
    >;

    "getLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tokenAAmount: BigNumber;
        tokenBAmount: BigNumber;
      }
    >;

    getReservesAfterArbitrage(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
    >;

    "getReservesAfterArbitrage(address,address,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
    >;
  };

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  getGasCostOfGetLiquidityValueAfterArbitrageToPrice(
    tokenA: string,
    tokenB: string,
    truePriceTokenA: BigNumberish,
    truePriceTokenB: BigNumberish,
    liquidityAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getGasCostOfGetLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
    tokenA: string,
    tokenB: string,
    truePriceTokenA: BigNumberish,
    truePriceTokenB: BigNumberish,
    liquidityAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLiquidityValue(
    tokenA: string,
    tokenB: string,
    liquidityAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      tokenAAmount: BigNumber;
      tokenBAmount: BigNumber;
    }
  >;

  "getLiquidityValue(address,address,uint256)"(
    tokenA: string,
    tokenB: string,
    liquidityAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      tokenAAmount: BigNumber;
      tokenBAmount: BigNumber;
    }
  >;

  getLiquidityValueAfterArbitrageToPrice(
    tokenA: string,
    tokenB: string,
    truePriceTokenA: BigNumberish,
    truePriceTokenB: BigNumberish,
    liquidityAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      tokenAAmount: BigNumber;
      tokenBAmount: BigNumber;
    }
  >;

  "getLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
    tokenA: string,
    tokenB: string,
    truePriceTokenA: BigNumberish,
    truePriceTokenB: BigNumberish,
    liquidityAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      tokenAAmount: BigNumber;
      tokenBAmount: BigNumber;
    }
  >;

  getReservesAfterArbitrage(
    tokenA: string,
    tokenB: string,
    truePriceTokenA: BigNumberish,
    truePriceTokenB: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
  >;

  "getReservesAfterArbitrage(address,address,uint256,uint256)"(
    tokenA: string,
    tokenB: string,
    truePriceTokenA: BigNumberish,
    truePriceTokenB: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
  >;

  callStatic: {
    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    getGasCostOfGetLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLiquidityValue(
      tokenA: string,
      tokenB: string,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tokenAAmount: BigNumber;
        tokenBAmount: BigNumber;
      }
    >;

    "getLiquidityValue(address,address,uint256)"(
      tokenA: string,
      tokenB: string,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tokenAAmount: BigNumber;
        tokenBAmount: BigNumber;
      }
    >;

    getLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tokenAAmount: BigNumber;
        tokenBAmount: BigNumber;
      }
    >;

    "getLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        tokenAAmount: BigNumber;
        tokenBAmount: BigNumber;
      }
    >;

    getReservesAfterArbitrage(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
    >;

    "getReservesAfterArbitrage(address,address,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { reserveA: BigNumber; reserveB: BigNumber }
    >;
  };

  filters: {};

  estimateGas: {
    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    getGasCostOfGetLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getGasCostOfGetLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLiquidityValue(
      tokenA: string,
      tokenB: string,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLiquidityValue(address,address,uint256)"(
      tokenA: string,
      tokenB: string,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReservesAfterArbitrage(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getReservesAfterArbitrage(address,address,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGasCostOfGetLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getGasCostOfGetLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidityValue(
      tokenA: string,
      tokenB: string,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLiquidityValue(address,address,uint256)"(
      tokenA: string,
      tokenB: string,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLiquidityValueAfterArbitrageToPrice(address,address,uint256,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReservesAfterArbitrage(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReservesAfterArbitrage(address,address,uint256,uint256)"(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
