/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IStakehoundGeyserInterface extends ethers.utils.Interface {
  functions: {
    "signalTokenLock(address,uint256,uint256,uint256)": FunctionFragment;
    "stake(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "signalTokenLock",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "signalTokenLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;

  events: {};
}

export class IStakehoundGeyser extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IStakehoundGeyserInterface;

  functions: {
    signalTokenLock(
      token: string,
      amount: BigNumberish,
      durationSec: BigNumberish,
      startTime: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "signalTokenLock(address,uint256,uint256,uint256)"(
      token: string,
      amount: BigNumberish,
      durationSec: BigNumberish,
      startTime: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    stake(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

    "stake(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  signalTokenLock(
    token: string,
    amount: BigNumberish,
    durationSec: BigNumberish,
    startTime: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "signalTokenLock(address,uint256,uint256,uint256)"(
    token: string,
    amount: BigNumberish,
    durationSec: BigNumberish,
    startTime: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  stake(arg0: string, overrides?: Overrides): Promise<ContractTransaction>;

  "stake(address)"(
    arg0: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    signalTokenLock(
      token: string,
      amount: BigNumberish,
      durationSec: BigNumberish,
      startTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "signalTokenLock(address,uint256,uint256,uint256)"(
      token: string,
      amount: BigNumberish,
      durationSec: BigNumberish,
      startTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stake(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "stake(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    signalTokenLock(
      token: string,
      amount: BigNumberish,
      durationSec: BigNumberish,
      startTime: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "signalTokenLock(address,uint256,uint256,uint256)"(
      token: string,
      amount: BigNumberish,
      durationSec: BigNumberish,
      startTime: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    stake(arg0: string, overrides?: Overrides): Promise<BigNumber>;

    "stake(address)"(arg0: string, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    signalTokenLock(
      token: string,
      amount: BigNumberish,
      durationSec: BigNumberish,
      startTime: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "signalTokenLock(address,uint256,uint256,uint256)"(
      token: string,
      amount: BigNumberish,
      durationSec: BigNumberish,
      startTime: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    stake(arg0: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "stake(address)"(
      arg0: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
