/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MerkleMockInterface extends ethers.utils.Interface {
  functions: {
    "computeHash(bytes32[],bytes32)": FunctionFragment;
    "verify(bytes32[],bytes32,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "computeHash",
    values: [BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike[], BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export class MerkleMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MerkleMockInterface;

  functions: {
    computeHash(
      proof: BytesLike[],
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "computeHash(bytes32[],bytes32)"(
      proof: BytesLike[],
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    verify(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "verify(bytes32[],bytes32,bytes32)"(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  computeHash(
    proof: BytesLike[],
    leaf: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "computeHash(bytes32[],bytes32)"(
    proof: BytesLike[],
    leaf: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  verify(
    proof: BytesLike[],
    root: BytesLike,
    leaf: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "verify(bytes32[],bytes32,bytes32)"(
    proof: BytesLike[],
    root: BytesLike,
    leaf: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    computeHash(
      proof: BytesLike[],
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "computeHash(bytes32[],bytes32)"(
      proof: BytesLike[],
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    verify(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "verify(bytes32[],bytes32,bytes32)"(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    computeHash(
      proof: BytesLike[],
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "computeHash(bytes32[],bytes32)"(
      proof: BytesLike[],
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verify(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "verify(bytes32[],bytes32,bytes32)"(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    computeHash(
      proof: BytesLike[],
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "computeHash(bytes32[],bytes32)"(
      proof: BytesLike[],
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "verify(bytes32[],bytes32,bytes32)"(
      proof: BytesLike[],
      root: BytesLike,
      leaf: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
