/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SmartVestingInterface extends ethers.utils.Interface {
  functions: {
    "__SingleTokenVestingNonRevocable_init(address,address,uint256,uint256,uint256)": FunctionFragment;
    "approveTransfer(address)": FunctionFragment;
    "beneficiary()": FunctionFragment;
    "call(address,uint256,bytes)": FunctionFragment;
    "claimEther()": FunctionFragment;
    "claimToken(address)": FunctionFragment;
    "cliff()": FunctionFragment;
    "duration()": FunctionFragment;
    "governor()": FunctionFragment;
    "initialize(address,address,address,uint256,uint256,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "releasableAmount()": FunctionFragment;
    "release()": FunctionFragment;
    "released()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeTransfer(address)": FunctionFragment;
    "start()": FunctionFragment;
    "token()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "__SingleTokenVestingNonRevocable_init",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveTransfer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "call",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimEther",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claimToken", values: [string]): string;
  encodeFunctionData(functionFragment: "cliff", values?: undefined): string;
  encodeFunctionData(functionFragment: "duration", values?: undefined): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releasableAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "release", values?: undefined): string;
  encodeFunctionData(functionFragment: "released", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTransfer",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "start", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "__SingleTokenVestingNonRevocable_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "call", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimEther", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cliff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "duration", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "released", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "ApproveTransfer(address)": EventFragment;
    "Call(address,uint256,bytes,bool)": EventFragment;
    "ClaimEther(uint256)": EventFragment;
    "ClaimToken(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RevokeTransfer(address)": EventFragment;
    "TokensReleased(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ApproveTransfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Call"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimEther"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevokeTransfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensReleased"): EventFragment;
}

export class SmartVesting extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SmartVestingInterface;

  functions: {
    __SingleTokenVestingNonRevocable_init(
      token: string,
      beneficiary: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "__SingleTokenVestingNonRevocable_init(address,address,uint256,uint256,uint256)"(
      token: string,
      beneficiary: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    approveTransfer(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approveTransfer(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    beneficiary(overrides?: CallOverrides): Promise<[string]>;

    "beneficiary()"(overrides?: CallOverrides): Promise<[string]>;

    call(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "call(address,uint256,bytes)"(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    claimEther(overrides?: Overrides): Promise<ContractTransaction>;

    "claimEther()"(overrides?: Overrides): Promise<ContractTransaction>;

    claimToken(
      tokenToClaim: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claimToken(address)"(
      tokenToClaim: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cliff(overrides?: CallOverrides): Promise<[BigNumber]>;

    "cliff()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    duration(overrides?: CallOverrides): Promise<[BigNumber]>;

    "duration()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    governor(overrides?: CallOverrides): Promise<[string]>;

    "governor()"(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      token: string,
      beneficiary: string,
      governor: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address,address,uint256,uint256,uint256)"(
      token: string,
      beneficiary: string,
      governor: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    releasableAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "releasableAmount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    release(overrides?: Overrides): Promise<ContractTransaction>;

    "release()"(overrides?: Overrides): Promise<ContractTransaction>;

    released(overrides?: CallOverrides): Promise<[BigNumber]>;

    "released()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    revokeTransfer(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeTransfer(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    start(overrides?: CallOverrides): Promise<[BigNumber]>;

    "start()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    token(overrides?: CallOverrides): Promise<[string]>;

    "token()"(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  __SingleTokenVestingNonRevocable_init(
    token: string,
    beneficiary: string,
    start: BigNumberish,
    cliffDuration: BigNumberish,
    duration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "__SingleTokenVestingNonRevocable_init(address,address,uint256,uint256,uint256)"(
    token: string,
    beneficiary: string,
    start: BigNumberish,
    cliffDuration: BigNumberish,
    duration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  approveTransfer(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approveTransfer(address)"(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  beneficiary(overrides?: CallOverrides): Promise<string>;

  "beneficiary()"(overrides?: CallOverrides): Promise<string>;

  call(
    to: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "call(address,uint256,bytes)"(
    to: string,
    value: BigNumberish,
    data: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  claimEther(overrides?: Overrides): Promise<ContractTransaction>;

  "claimEther()"(overrides?: Overrides): Promise<ContractTransaction>;

  claimToken(
    tokenToClaim: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claimToken(address)"(
    tokenToClaim: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cliff(overrides?: CallOverrides): Promise<BigNumber>;

  "cliff()"(overrides?: CallOverrides): Promise<BigNumber>;

  duration(overrides?: CallOverrides): Promise<BigNumber>;

  "duration()"(overrides?: CallOverrides): Promise<BigNumber>;

  governor(overrides?: CallOverrides): Promise<string>;

  "governor()"(overrides?: CallOverrides): Promise<string>;

  initialize(
    token: string,
    beneficiary: string,
    governor: string,
    start: BigNumberish,
    cliffDuration: BigNumberish,
    duration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address,address,uint256,uint256,uint256)"(
    token: string,
    beneficiary: string,
    governor: string,
    start: BigNumberish,
    cliffDuration: BigNumberish,
    duration: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  releasableAmount(overrides?: CallOverrides): Promise<BigNumber>;

  "releasableAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

  release(overrides?: Overrides): Promise<ContractTransaction>;

  "release()"(overrides?: Overrides): Promise<ContractTransaction>;

  released(overrides?: CallOverrides): Promise<BigNumber>;

  "released()"(overrides?: CallOverrides): Promise<BigNumber>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  revokeTransfer(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeTransfer(address)"(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  start(overrides?: CallOverrides): Promise<BigNumber>;

  "start()"(overrides?: CallOverrides): Promise<BigNumber>;

  token(overrides?: CallOverrides): Promise<string>;

  "token()"(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    __SingleTokenVestingNonRevocable_init(
      token: string,
      beneficiary: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "__SingleTokenVestingNonRevocable_init(address,address,uint256,uint256,uint256)"(
      token: string,
      beneficiary: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    approveTransfer(to: string, overrides?: CallOverrides): Promise<void>;

    "approveTransfer(address)"(
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    beneficiary(overrides?: CallOverrides): Promise<string>;

    "beneficiary()"(overrides?: CallOverrides): Promise<string>;

    call(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "call(address,uint256,bytes)"(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    claimEther(overrides?: CallOverrides): Promise<void>;

    "claimEther()"(overrides?: CallOverrides): Promise<void>;

    claimToken(tokenToClaim: string, overrides?: CallOverrides): Promise<void>;

    "claimToken(address)"(
      tokenToClaim: string,
      overrides?: CallOverrides
    ): Promise<void>;

    cliff(overrides?: CallOverrides): Promise<BigNumber>;

    "cliff()"(overrides?: CallOverrides): Promise<BigNumber>;

    duration(overrides?: CallOverrides): Promise<BigNumber>;

    "duration()"(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<string>;

    "governor()"(overrides?: CallOverrides): Promise<string>;

    initialize(
      token: string,
      beneficiary: string,
      governor: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address,address,uint256,uint256,uint256)"(
      token: string,
      beneficiary: string,
      governor: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    releasableAmount(overrides?: CallOverrides): Promise<BigNumber>;

    "releasableAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

    release(overrides?: CallOverrides): Promise<void>;

    "release()"(overrides?: CallOverrides): Promise<void>;

    released(overrides?: CallOverrides): Promise<BigNumber>;

    "released()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    revokeTransfer(to: string, overrides?: CallOverrides): Promise<void>;

    "revokeTransfer(address)"(
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    start(overrides?: CallOverrides): Promise<BigNumber>;

    "start()"(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<string>;

    "token()"(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ApproveTransfer(to: null): EventFilter;

    Call(
      to: null,
      value: null,
      data: null,
      transfersAllowed: null
    ): EventFilter;

    ClaimEther(amount: null): EventFilter;

    ClaimToken(token: null, amount: null): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    RevokeTransfer(to: null): EventFilter;

    TokensReleased(token: null, amount: null): EventFilter;
  };

  estimateGas: {
    __SingleTokenVestingNonRevocable_init(
      token: string,
      beneficiary: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "__SingleTokenVestingNonRevocable_init(address,address,uint256,uint256,uint256)"(
      token: string,
      beneficiary: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    approveTransfer(to: string, overrides?: Overrides): Promise<BigNumber>;

    "approveTransfer(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    beneficiary(overrides?: CallOverrides): Promise<BigNumber>;

    "beneficiary()"(overrides?: CallOverrides): Promise<BigNumber>;

    call(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "call(address,uint256,bytes)"(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    claimEther(overrides?: Overrides): Promise<BigNumber>;

    "claimEther()"(overrides?: Overrides): Promise<BigNumber>;

    claimToken(tokenToClaim: string, overrides?: Overrides): Promise<BigNumber>;

    "claimToken(address)"(
      tokenToClaim: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cliff(overrides?: CallOverrides): Promise<BigNumber>;

    "cliff()"(overrides?: CallOverrides): Promise<BigNumber>;

    duration(overrides?: CallOverrides): Promise<BigNumber>;

    "duration()"(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    "governor()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      token: string,
      beneficiary: string,
      governor: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address,address,uint256,uint256,uint256)"(
      token: string,
      beneficiary: string,
      governor: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    releasableAmount(overrides?: CallOverrides): Promise<BigNumber>;

    "releasableAmount()"(overrides?: CallOverrides): Promise<BigNumber>;

    release(overrides?: Overrides): Promise<BigNumber>;

    "release()"(overrides?: Overrides): Promise<BigNumber>;

    released(overrides?: CallOverrides): Promise<BigNumber>;

    "released()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    revokeTransfer(to: string, overrides?: Overrides): Promise<BigNumber>;

    "revokeTransfer(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    start(overrides?: CallOverrides): Promise<BigNumber>;

    "start()"(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    "token()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    __SingleTokenVestingNonRevocable_init(
      token: string,
      beneficiary: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "__SingleTokenVestingNonRevocable_init(address,address,uint256,uint256,uint256)"(
      token: string,
      beneficiary: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    approveTransfer(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approveTransfer(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    beneficiary(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "beneficiary()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    call(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "call(address,uint256,bytes)"(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    claimEther(overrides?: Overrides): Promise<PopulatedTransaction>;

    "claimEther()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    claimToken(
      tokenToClaim: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claimToken(address)"(
      tokenToClaim: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cliff(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cliff()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    duration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "duration()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "governor()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      token: string,
      beneficiary: string,
      governor: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address,address,uint256,uint256,uint256)"(
      token: string,
      beneficiary: string,
      governor: string,
      start: BigNumberish,
      cliffDuration: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    releasableAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "releasableAmount()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    release(overrides?: Overrides): Promise<PopulatedTransaction>;

    "release()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    released(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "released()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    revokeTransfer(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeTransfer(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    start(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "start()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "token()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
