/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface StakedTokenInterface extends ethers.utils.Interface {
  functions: {
    "addTransaction(address,bytes)": FunctionFragment;
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "burn(uint256)": FunctionFragment;
    "decimals()": FunctionFragment;
    "decreaseAllowance(address,uint256)": FunctionFragment;
    "distributeTokens(uint256,bool)": FunctionFragment;
    "downstreamCaller()": FunctionFragment;
    "downstreamCallerAddress()": FunctionFragment;
    "increaseAllowance(address,uint256)": FunctionFragment;
    "initialize(string,string,uint8,uint256,uint256)": FunctionFragment;
    "isBlacklisted(address)": FunctionFragment;
    "mint(address,uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "removeTransaction(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setBlacklisted(address,bool)": FunctionFragment;
    "setDownstreamCaller(address)": FunctionFragment;
    "setName(string)": FunctionFragment;
    "setSupplyController(address)": FunctionFragment;
    "setSymbol(string)": FunctionFragment;
    "setTransactionEnabled(uint256,bool)": FunctionFragment;
    "sharesOf(address)": FunctionFragment;
    "supplyController()": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalShares()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transactionsSize()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addTransaction",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeTokens",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "downstreamCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "downstreamCallerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBlacklisted",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDownstreamCaller",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setSupplyController",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setSymbol", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setTransactionEnabled",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "sharesOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supplyController",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactionsSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "downstreamCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "downstreamCallerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDownstreamCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSymbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTransactionEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sharesOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supplyController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactionsSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "Blacklisted(address,bool)": EventFragment;
    "LogSupplyControllerUpdated(address)": EventFragment;
    "LogTokenDistribution(uint256,uint256,bool,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "WarningMaxExpectedSupplyExceeded(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Blacklisted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogSupplyControllerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTokenDistribution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "WarningMaxExpectedSupplyExceeded"
  ): EventFragment;
}

export class StakedToken extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: StakedTokenInterface;

  functions: {
    addTransaction(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addTransaction(address,bytes)"(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    allowance(
      owner_: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "allowance(address,address)"(
      owner_: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      spender: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balanceOf(who: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "balanceOf(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    burn(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burn(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    "decimals()"(overrides?: CallOverrides): Promise<[number]>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    distributeTokens(
      supplyChange_: BigNumberish,
      positive: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "distributeTokens(uint256,bool)"(
      supplyChange_: BigNumberish,
      positive: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    downstreamCaller(overrides?: CallOverrides): Promise<[string]>;

    "downstreamCaller()"(overrides?: CallOverrides): Promise<[string]>;

    downstreamCallerAddress(overrides?: CallOverrides): Promise<[string]>;

    "downstreamCallerAddress()"(overrides?: CallOverrides): Promise<[string]>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(
      name_: string,
      symbol_: string,
      decimals_: BigNumberish,
      maxExpectedSupply_: BigNumberish,
      initialSupply_: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(string,string,uint8,uint256,uint256)"(
      name_: string,
      symbol_: string,
      decimals_: BigNumberish,
      maxExpectedSupply_: BigNumberish,
      initialSupply_: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    isBlacklisted(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isBlacklisted(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    mint(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mint(address,uint256)"(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    "name()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    pause(overrides?: Overrides): Promise<ContractTransaction>;

    "pause()"(overrides?: Overrides): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    "paused()"(overrides?: CallOverrides): Promise<[boolean]>;

    removeTransaction(
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeTransaction(uint256)"(
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    setBlacklisted(
      account: string,
      _isBlacklisted: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setBlacklisted(address,bool)"(
      account: string,
      _isBlacklisted: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setDownstreamCaller(
      _downstreamCaller: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setDownstreamCaller(address)"(
      _downstreamCaller: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setName(name_: string, overrides?: Overrides): Promise<ContractTransaction>;

    "setName(string)"(
      name_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setSupplyController(
      supplyController_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setSupplyController(address)"(
      supplyController_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setSymbol(
      symbol_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setSymbol(string)"(
      symbol_: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setTransactionEnabled(
      index: BigNumberish,
      enabled: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setTransactionEnabled(uint256,bool)"(
      index: BigNumberish,
      enabled: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sharesOf(who: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "sharesOf(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    supplyController(overrides?: CallOverrides): Promise<[string]>;

    "supplyController()"(overrides?: CallOverrides): Promise<[string]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    "symbol()"(overrides?: CallOverrides): Promise<[string]>;

    totalShares(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalShares()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalSupply()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transactionsSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    "transactionsSize()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferFrom(
      from: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    unpause(overrides?: Overrides): Promise<ContractTransaction>;

    "unpause()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  addTransaction(
    destination: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addTransaction(address,bytes)"(
    destination: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  allowance(
    owner_: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "allowance(address,address)"(
    owner_: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    spender: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balanceOf(who: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    who: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  burn(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burn(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  decimals(overrides?: CallOverrides): Promise<number>;

  "decimals()"(overrides?: CallOverrides): Promise<number>;

  decreaseAllowance(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "decreaseAllowance(address,uint256)"(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  distributeTokens(
    supplyChange_: BigNumberish,
    positive: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "distributeTokens(uint256,bool)"(
    supplyChange_: BigNumberish,
    positive: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  downstreamCaller(overrides?: CallOverrides): Promise<string>;

  "downstreamCaller()"(overrides?: CallOverrides): Promise<string>;

  downstreamCallerAddress(overrides?: CallOverrides): Promise<string>;

  "downstreamCallerAddress()"(overrides?: CallOverrides): Promise<string>;

  increaseAllowance(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseAllowance(address,uint256)"(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(
    name_: string,
    symbol_: string,
    decimals_: BigNumberish,
    maxExpectedSupply_: BigNumberish,
    initialSupply_: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(string,string,uint8,uint256,uint256)"(
    name_: string,
    symbol_: string,
    decimals_: BigNumberish,
    maxExpectedSupply_: BigNumberish,
    initialSupply_: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  isBlacklisted(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "isBlacklisted(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  mint(
    account: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mint(address,uint256)"(
    account: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  pause(overrides?: Overrides): Promise<ContractTransaction>;

  "pause()"(overrides?: Overrides): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  removeTransaction(
    index: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeTransaction(uint256)"(
    index: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  setBlacklisted(
    account: string,
    _isBlacklisted: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setBlacklisted(address,bool)"(
    account: string,
    _isBlacklisted: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setDownstreamCaller(
    _downstreamCaller: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setDownstreamCaller(address)"(
    _downstreamCaller: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setName(name_: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setName(string)"(
    name_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setSupplyController(
    supplyController_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setSupplyController(address)"(
    supplyController_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setSymbol(
    symbol_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setSymbol(string)"(
    symbol_: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setTransactionEnabled(
    index: BigNumberish,
    enabled: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setTransactionEnabled(uint256,bool)"(
    index: BigNumberish,
    enabled: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sharesOf(who: string, overrides?: CallOverrides): Promise<BigNumber>;

  "sharesOf(address)"(
    who: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  supplyController(overrides?: CallOverrides): Promise<string>;

  "supplyController()"(overrides?: CallOverrides): Promise<string>;

  symbol(overrides?: CallOverrides): Promise<string>;

  "symbol()"(overrides?: CallOverrides): Promise<string>;

  totalShares(overrides?: CallOverrides): Promise<BigNumber>;

  "totalShares()"(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  transactionsSize(overrides?: CallOverrides): Promise<BigNumber>;

  "transactionsSize()"(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    to: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    to: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferFrom(
    from: string,
    to: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    from: string,
    to: string,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  unpause(overrides?: Overrides): Promise<ContractTransaction>;

  "unpause()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    addTransaction(
      destination: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addTransaction(address,bytes)"(
      destination: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allowance(
      owner_: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      owner_: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "approve(address,uint256)"(
      spender: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(who: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burn(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "burn(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    decimals(overrides?: CallOverrides): Promise<number>;

    "decimals()"(overrides?: CallOverrides): Promise<number>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    distributeTokens(
      supplyChange_: BigNumberish,
      positive: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "distributeTokens(uint256,bool)"(
      supplyChange_: BigNumberish,
      positive: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    downstreamCaller(overrides?: CallOverrides): Promise<string>;

    "downstreamCaller()"(overrides?: CallOverrides): Promise<string>;

    downstreamCallerAddress(overrides?: CallOverrides): Promise<string>;

    "downstreamCallerAddress()"(overrides?: CallOverrides): Promise<string>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      name_: string,
      symbol_: string,
      decimals_: BigNumberish,
      maxExpectedSupply_: BigNumberish,
      initialSupply_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(string,string,uint8,uint256,uint256)"(
      name_: string,
      symbol_: string,
      decimals_: BigNumberish,
      maxExpectedSupply_: BigNumberish,
      initialSupply_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    isBlacklisted(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "isBlacklisted(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    mint(
      account: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "mint(address,uint256)"(
      account: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    "pause()"(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    removeTransaction(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeTransaction(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    setBlacklisted(
      account: string,
      _isBlacklisted: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setBlacklisted(address,bool)"(
      account: string,
      _isBlacklisted: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setDownstreamCaller(
      _downstreamCaller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setDownstreamCaller(address)"(
      _downstreamCaller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setName(name_: string, overrides?: CallOverrides): Promise<void>;

    "setName(string)"(name_: string, overrides?: CallOverrides): Promise<void>;

    setSupplyController(
      supplyController_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setSupplyController(address)"(
      supplyController_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSymbol(symbol_: string, overrides?: CallOverrides): Promise<void>;

    "setSymbol(string)"(
      symbol_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTransactionEnabled(
      index: BigNumberish,
      enabled: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setTransactionEnabled(uint256,bool)"(
      index: BigNumberish,
      enabled: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    sharesOf(who: string, overrides?: CallOverrides): Promise<BigNumber>;

    "sharesOf(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supplyController(overrides?: CallOverrides): Promise<string>;

    "supplyController()"(overrides?: CallOverrides): Promise<string>;

    symbol(overrides?: CallOverrides): Promise<string>;

    "symbol()"(overrides?: CallOverrides): Promise<string>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;

    "totalShares()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transactionsSize(overrides?: CallOverrides): Promise<BigNumber>;

    "transactionsSize()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transfer(address,uint256)"(
      to: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      from: string,
      to: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    "unpause()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): EventFilter;

    Blacklisted(account: string | null, isBlacklisted: null): EventFilter;

    LogSupplyControllerUpdated(supplyController: null): EventFilter;

    LogTokenDistribution(
      oldTotalSupply: null,
      supplyChange: null,
      positive: null,
      newTotalSupply: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    Paused(account: null): EventFilter;

    Transfer(from: string | null, to: string | null, value: null): EventFilter;

    Unpaused(account: null): EventFilter;

    WarningMaxExpectedSupplyExceeded(
      totalSupply: null,
      totalShares: null
    ): EventFilter;
  };

  estimateGas: {
    addTransaction(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addTransaction(address,bytes)"(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    allowance(
      owner_: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      owner_: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      spender: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balanceOf(who: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burn(amount: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "burn(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    distributeTokens(
      supplyChange_: BigNumberish,
      positive: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "distributeTokens(uint256,bool)"(
      supplyChange_: BigNumberish,
      positive: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    downstreamCaller(overrides?: CallOverrides): Promise<BigNumber>;

    "downstreamCaller()"(overrides?: CallOverrides): Promise<BigNumber>;

    downstreamCallerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "downstreamCallerAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(
      name_: string,
      symbol_: string,
      decimals_: BigNumberish,
      maxExpectedSupply_: BigNumberish,
      initialSupply_: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(string,string,uint8,uint256,uint256)"(
      name_: string,
      symbol_: string,
      decimals_: BigNumberish,
      maxExpectedSupply_: BigNumberish,
      initialSupply_: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    isBlacklisted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isBlacklisted(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mint(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mint(address,uint256)"(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    pause(overrides?: Overrides): Promise<BigNumber>;

    "pause()"(overrides?: Overrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    removeTransaction(
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeTransaction(uint256)"(
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    setBlacklisted(
      account: string,
      _isBlacklisted: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setBlacklisted(address,bool)"(
      account: string,
      _isBlacklisted: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setDownstreamCaller(
      _downstreamCaller: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setDownstreamCaller(address)"(
      _downstreamCaller: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setName(name_: string, overrides?: Overrides): Promise<BigNumber>;

    "setName(string)"(name_: string, overrides?: Overrides): Promise<BigNumber>;

    setSupplyController(
      supplyController_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setSupplyController(address)"(
      supplyController_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setSymbol(symbol_: string, overrides?: Overrides): Promise<BigNumber>;

    "setSymbol(string)"(
      symbol_: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setTransactionEnabled(
      index: BigNumberish,
      enabled: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setTransactionEnabled(uint256,bool)"(
      index: BigNumberish,
      enabled: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sharesOf(who: string, overrides?: CallOverrides): Promise<BigNumber>;

    "sharesOf(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supplyController(overrides?: CallOverrides): Promise<BigNumber>;

    "supplyController()"(overrides?: CallOverrides): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;

    "totalShares()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transactionsSize(overrides?: CallOverrides): Promise<BigNumber>;

    "transactionsSize()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    unpause(overrides?: Overrides): Promise<BigNumber>;

    "unpause()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addTransaction(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addTransaction(address,bytes)"(
      destination: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    allowance(
      owner_: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allowance(address,address)"(
      owner_: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approve(address,uint256)"(
      spender: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    burn(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burn(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "decimals()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    distributeTokens(
      supplyChange_: BigNumberish,
      positive: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "distributeTokens(uint256,bool)"(
      supplyChange_: BigNumberish,
      positive: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    downstreamCaller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "downstreamCaller()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    downstreamCallerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "downstreamCallerAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(
      name_: string,
      symbol_: string,
      decimals_: BigNumberish,
      maxExpectedSupply_: BigNumberish,
      initialSupply_: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(string,string,uint8,uint256,uint256)"(
      name_: string,
      symbol_: string,
      decimals_: BigNumberish,
      maxExpectedSupply_: BigNumberish,
      initialSupply_: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isBlacklisted(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isBlacklisted(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mint(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mint(address,uint256)"(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(overrides?: Overrides): Promise<PopulatedTransaction>;

    "pause()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeTransaction(
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeTransaction(uint256)"(
      index: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    setBlacklisted(
      account: string,
      _isBlacklisted: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setBlacklisted(address,bool)"(
      account: string,
      _isBlacklisted: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setDownstreamCaller(
      _downstreamCaller: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setDownstreamCaller(address)"(
      _downstreamCaller: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setName(
      name_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setName(string)"(
      name_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setSupplyController(
      supplyController_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setSupplyController(address)"(
      supplyController_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setSymbol(
      symbol_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setSymbol(string)"(
      symbol_: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setTransactionEnabled(
      index: BigNumberish,
      enabled: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setTransactionEnabled(uint256,bool)"(
      index: BigNumberish,
      enabled: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sharesOf(
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sharesOf(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supplyController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "supplyController()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "symbol()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalShares()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalSupply()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transactionsSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "transactionsSize()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transfer(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    unpause(overrides?: Overrides): Promise<PopulatedTransaction>;

    "unpause()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
