/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StakedToken } from "./StakedToken";

export { StakedToken__factory } from "./factories/StakedToken__factory";
